### ISSUE TITLE
Improvement request: copy to drive with most free space

### ISSUE THREAD

**Issue by PanzerKunst** [lmacken/plow#6]
The current implementation loops through the list of dest drives. What do you think if the script would instead transfer to the drive with the most free space, provided it has no ongoing copy happening?

**Comment by lmacken** [comment]
There is a fork of the plow that already has the ability to check the amount of the free space of the destinations:

https://github.com/graemes/mownplow

Closing this ticket since I feel like it's a little out of scope for this simplified version, and I'm not sure if we can even query how much free space is left via rsyncd.
